CREATE DATABASE `empMgmt` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

CREATE TABLE `EMPLOYEE` (
  `EMPLOYEEID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEENAME` varchar(45) DEFAULT NULL,
  `SSN` varchar(45) DEFAULT NULL,
  `DESIGNATION` varchar(45) DEFAULT NULL,
  `DEPARTMENT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEEID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

